/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "radykgcbygmkngnemzvh"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJhZHlrZ2NieWdta25nbmVtenZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI4MDM4NDIsImV4cCI6MjA4ODM3OTg0Mn0.tg-8_xFbBzPbTcdjZT8k1TmUJuBvosy-fTIcfALeRJ8"